## Diversifiable and Non-Diversifiable Risk of a Portfolio

Import the same dataset we used in the previous lecture – Microsoft and Apple stock. Timeframe – 1st of January 2000 until today. <br />
*Hint: To save time, we have written the code you need!*

In [1]:
import numpy as np
import pandas as pd
from pandas_datareader import data as wb
import matplotlib.pyplot as plt

sec_data = pd.read_csv(r'C:\Users\Admin\OneDrive\Documents\bt ptdl\bt_tuan_ptdl\DA07 - Phan tich du lieu tai chinh\02_risks\02_risks\04_Diversifiable and Non-Diversifiable Risk\04_Diversifiable and Non-Diversifiable Risk\csv\MSFT_AAPL_2000_2017.csv', index_col='Date')
sec_data

                 MSFT        AAPL
Date
1999-12-31  38.965767    3.303425
2000-01-03  38.903194    3.596616
2000-01-04  37.589046    3.293384
2000-01-05  37.985374    3.341579
2000-01-06  36.712940    3.052405
...               ...         ...
2017-03-17  64.158463  138.869217
2017-03-20  64.217804  140.327454
2017-03-21  63.505699  138.720413
2017-03-22  64.316704  140.287766
2017-03-23  64.158463  139.791763

[4334 rows x 2 columns]

In [2]:
sec_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4334 entries, 1999-12-31 to 2017-03-23
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   MSFT    4334 non-null   float64
 1   AAPL    4334 non-null   float64
dtypes: float64(2)
memory usage: 101.6+ KB

Then, calculate the diversifiable and the non-diversifiable risk of a portfolio, composed of these two stocks:

a) with weights 0.5 and 0.5;

In [3]:
sec_returns = np.log(sec_data / sec_data.shift(1))
sec_returns

                MSFT      AAPL
Date
1999-12-31       NaN       NaN
2000-01-03 -0.001607  0.085034
2000-01-04 -0.034364 -0.088078
2000-01-05  0.010489  0.014528
2000-01-06 -0.034072 -0.090514
...              ...       ...
2017-03-17  0.003552 -0.004988
2017-03-20  0.000924  0.010446
2017-03-21 -0.011151 -0.011518
2017-03-22  0.012690  0.011235
2017-03-23 -0.002463 -0.003542

[4334 rows x 2 columns]

### Calculating Portfolio Variance

Equal weightings scheme:

In [4]:
weights = np.array([0.5, 0.5])

Portfolio Variance:

In [5]:
pfolio_var = np.dot(weights.T, np.dot(sec_returns.cov() * 250, weights))
pfolio_var

np.float64(0.09961622870546066)

### Calculating Diversifiable and Non-Diversifiable Risk of a Portfolio

Diversifiable Risk:

In [6]:
MSFT_var_a = sec_returns[['MSFT']].var() * 250
MSFT_var_a

MSFT    0.096599
dtype: float64

In [7]:
AAPL_var_a = sec_returns[['AAPL']].var() * 250
AAPL_var_a

AAPL    0.192681
dtype: float64

Or:

In [8]:
MSFT_var_a = sec_returns['MSFT'].var() * 250
MSFT_var_a

np.float64(0.0965989095170177)

In [9]:
AAPL_var_a = sec_returns['AAPL'].var() * 250
AAPL_var_a

np.float64(0.19268124918691418)

Calculating Diversifiable Risk:

In [10]:
dr = pfolio_var - (weights[0] ** 2 * MSFT_var_a) - (weights[1] ** 2 * AAPL_var_a)
dr

np.float64(0.02729618902947769)

In [11]:
print (str(round(dr*100, 3)) + ' %')

2.73 %

Calculating Non-Diversifiable Risk:

In [12]:
n_dr_1 = pfolio_var - dr
n_dr_1

np.float64(0.07232003967598297)

In [13]:
n_dr_2 = (weights[0] ** 2 * MSFT_var_a) + (weights[1] ** 2 * AAPL_var_a)
n_dr_2

np.float64(0.07232003967598297)

*****

b)	With weights 0.2 for Microsoft and 0.8 for Apple.

### Calculating Portfolio Variance

In [14]:
weights_2 = np.array([0.2, 0.8])

Portfolio Variance:

In [15]:
pfolio_var_2 = np.dot(weights_2.T, np.dot(sec_returns.cov() * 250, weights_2))
pfolio_var_2

np.float64(0.14464951683917135)

### Calculating Diversifiable and Non-Diversifiable Risk of a Portfolio

Calculating Diversifiable Risk:

In [16]:
dr_2 = pfolio_var_2 - (weights_2[0] ** 2 * MSFT_var_a) - (weights_2[1] ** 2 * AAPL_var_a)
dr_2

np.float64(0.01746956097886554)

In [17]:
print (str(round(dr*100, 3)) + ' %')

2.73 %

Calculating Non-Diversifiable Risk:

In [18]:
n_dr_2 = pfolio_var_2 - dr_2
n_dr_2

np.float64(0.1271799558603058)

In [19]:
n_dr_2 = (weights_2[0] ** 2 * MSFT_var_a) + (weights_2[1] ** 2 * AAPL_var_a)
n_dr_2

np.float64(0.1271799558603058)