## Calculating the Beta of a Stock

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Load the data for Microsoft and S&P 500 for the period 1st of January 2012 – 31st of December 2016.

In [1]:
import numpy as np
import pandas as pd
from pandas_datareader import data as wb

data = pd.read_csv(r'C:\Users\Admin\OneDrive\Documents\bt ptdl\bt_tuan_ptdl\DA07 - Phan tich du lieu tai chinh\04_normative_finance\04_normative_finance\04_Calculating the Beta of a Stock\csv\CAPM_Exercise_Data.csv', index_col = 'Date')
data

                 MSFT        ^GSPC
Date
2012-01-03  23.031868  1277.060059
2012-01-04  23.573898  1277.300049
2012-01-05  23.814798  1281.060059
2012-01-06  24.184755  1277.810059
2012-01-09  23.866419  1280.699951
...               ...          ...
2016-12-23  62.500671  2263.790039
2016-12-27  62.540195  2268.879883
2016-12-28  62.253590  2249.919922
2016-12-29  62.164646  2249.260010
2016-12-30  61.413525  2238.830078

[1258 rows x 2 columns]

Let S&P 500 act as the market.

*****

Calculate the beta of Microsoft.

In [2]:
sec_returns = np.log( data / data.shift(1) )

In [3]:
cov = sec_returns.cov() * 250
cov

           MSFT     ^GSPC
MSFT   0.053781  0.018208
^GSPC  0.018208  0.016361

In [4]:
cov_with_market = cov.iloc[0,1]
cov_with_market

np.float64(0.018208431910398934)

In [5]:
market_var = sec_returns['^GSPC'].var() * 250
market_var

np.float64(0.01636059269926906)

** Beta: **
### $$ 
\beta_{pg} = \frac{\sigma_{pg,m}}{\sigma_{m}^2}
$$

In [6]:
MSFT_beta = cov_with_market / market_var
MSFT_beta

np.float64(1.1129445152199424)