## Simpler Returns - Part I

Download the data for Microsoft (‘MSFT’) from IEX for the period ‘2015-1-1’ until today.

In [25]:
import numpy as np
from pandas_datareader import data as wb
import matplotlib.pyplot as plt
import datetime as dt
import yfinance as yf

In [26]:
start = dt.datetime(2015, 1, 1)
end = dt.datetime.now()

PG = yf.download('PG', start=start, end=end)

C:\Users\Admin\AppData\Local\Temp\ipykernel_22280\1541741690.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  PG = yf.download('PG', start=start, end=end)
[*********************100%***********************]  1 of 1 completed

Apply the .**head()** and **.tail()** methods to check if the data is ok. Always pay attention to the dates. Try to get an idea about how the stock price changed during the period.

In [27]:
PG.head()

Price           Close       High        Low       Open   Volume
Ticker             PG         PG         PG         PG       PG
Date
2015-01-02  66.518333  66.930210  66.135872  66.812528  7251400
2015-01-05  66.202057  66.930197  66.084375  66.363867  8626100
2015-01-06  65.900528  66.606604  65.650462  66.422730  7791200
2015-01-07  66.246216  66.466867  65.871111  66.150603  5986600
2015-01-08  67.003784  67.099402  66.290351  66.547780  6823300

In [28]:
PG.tail()

Price            Close        High         Low        Open    Volume
Ticker              PG          PG          PG          PG        PG
Date
2025-10-23  151.153000  152.235427  149.534314  151.292027   8205400
2025-10-24  152.490005  157.399994  151.529999  156.399994  11968500
2025-10-27  151.740005  151.759995  150.130005  151.610001   7775300
2025-10-28  151.369995  153.169998  150.619995  151.119995   5819300
2025-10-29  148.770004  150.970001  148.470001  150.660004   7401100

### Simple Rate of Return

Calculate the simple returns of ‘MSFT’ for the given timeframe.

$$
\frac{P_1 - P_0}{P_0} = \frac{P_1}{P_0} - 1
$$

In [30]:
PG['simple_return'] = (PG['Close'] / PG['Close'].shift(1)) - 1
print (PG['simple_return'])

Date
2015-01-02         NaN
2015-01-05   -0.004755
2015-01-06   -0.004555
2015-01-07    0.005246
2015-01-08    0.011436
                ...
2025-10-23    0.000066
2025-10-24    0.008845
2025-10-27   -0.004918
2025-10-28   -0.002438
2025-10-29   -0.017176
Name: simple_return, Length: 2723, dtype: float64