## Calculating Portfolio Risk

Calculate the risk of an equally weighted portfolio composed of Microsoft and Apple. The data can be obtained from IEX for the period 1st of January 2007 until today.

*Hint: The code we went through in the lecture is what you need here. You will need to import the data first. The previous lessons could be a good reference point for that! :) *

In [1]:
import numpy as np
import pandas as pd
from pandas_datareader import data as wb
import matplotlib.pyplot as plt
import yfinance as yf

In [2]:
tickers = ['MSFT', 'AAPL']

sec_data = pd.DataFrame()

for t in tickers:
    sec_data[t] = yf.download(t, start='2015-1-1')['Close']

C:\Users\Admin\AppData\Local\Temp\ipykernel_16584\480671726.py:6: FutureWarning: YF.download() has changed argument auto_adjust default to True
  sec_data[t] = yf.download(t, start='2015-1-1')['Close']
[*********************100%***********************]  1 of 1 completed
C:\Users\Admin\AppData\Local\Temp\ipykernel_16584\480671726.py:6: FutureWarning: YF.download() has changed argument auto_adjust default to True
  sec_data[t] = yf.download(t, start='2015-1-1')['Close']
[*********************100%***********************]  1 of 1 completed

In [3]:
sec_data.tail()

                  MSFT        AAPL
Date
2025-10-23  520.559998  259.579987
2025-10-24  523.609985  262.820007
2025-10-27  531.520020  268.809998
2025-10-28  542.070007  269.000000
2025-10-29  541.549988  269.700012

In [4]:
sec_returns = np.log(sec_data / sec_data.shift(1))

In [5]:
sec_returns

                MSFT      AAPL
Date
2015-01-02       NaN       NaN
2015-01-05 -0.009239 -0.028576
2015-01-06 -0.014786  0.000094
2015-01-07  0.012626  0.013925
2015-01-08  0.028994  0.037703
...              ...       ...
2025-10-23  0.000038  0.004363
2025-10-24  0.005842  0.012405
2025-10-27  0.014994  0.022535
2025-10-28  0.019654  0.000707
2025-10-29 -0.000960  0.002599

[2723 rows x 2 columns]

## MSFT

In [6]:
sec_returns['MSFT'].mean()

np.float64(0.0009578363850628195)

In [7]:
sec_returns['MSFT'].mean() * 250

np.float64(0.23945909626570488)

In [8]:
sec_returns['MSFT'].std()

np.float64(0.01697580716579484)

In [9]:
sec_returns['MSFT'].std() * 250 ** 0.5

np.float64(0.26841107881859655)

## Apple

In [10]:
sec_returns['AAPL'].mean()

np.float64(0.0008848046579741384)

In [11]:
sec_returns['AAPL'].mean() * 250

np.float64(0.2212011644935346)

In [12]:
sec_returns['AAPL'].std()

np.float64(0.018267342206917933)

In [13]:
sec_returns['AAPL'].std() * 250 ** 0.5

np.float64(0.28883204085793757)

***

In [14]:
sec_returns[['MSFT', 'AAPL']].mean() * 250

MSFT    0.239459
AAPL    0.221201
dtype: float64

In [15]:
sec_returns[['MSFT', 'AAPL']].std() * 250 ** 0.5

MSFT    0.268411
AAPL    0.288832
dtype: float64

## Covariance and Correlation


\begin{eqnarray*}
Covariance Matrix: \  \   
\Sigma = \begin{bmatrix}
        \sigma_{1}^2 \ \sigma_{12} \ \dots \ \sigma_{1I} \\
        \sigma_{21} \ \sigma_{2}^2 \ \dots \ \sigma_{2I} \\
        \vdots \ \vdots \ \ddots \ \vdots \\
        \sigma_{I1} \ \sigma_{I2} \ \dots \ \sigma_{I}^2
    \end{bmatrix}
\end{eqnarray*}

*****

Covariance matrix:

In [16]:
cov_matrix = sec_returns.cov()
cov_matrix

          MSFT      AAPL
MSFT  0.000288  0.000207
AAPL  0.000207  0.000334

***

Correlation matrix:

In [17]:
cov_matrix_a = sec_returns.cov() * 250
cov_matrix_a

          MSFT      AAPL
MSFT  0.072045  0.051838
AAPL  0.051838  0.083424

In [18]:
corr_matrix = sec_returns.corr()
corr_matrix

          MSFT      AAPL
MSFT  1.000000  0.668659
AAPL  0.668659  1.000000

## Calculating Portfolio Risk

Equal weigthing scheme:

In [19]:
weights = np.array([0.5, 0.5])

Portfolio Variance:

In [20]:
pfolio_var = np.dot(weights.T, np.dot(sec_returns.cov() * 250, weights))
pfolio_var

np.float64(0.06478624558377735)

Portfolio Volatility:

In [21]:
pfolio_vol = (np.dot(weights.T, np.dot(sec_returns.cov() * 250, weights))) ** 0.5
pfolio_vol

np.float64(0.25453142356844144)

In [22]:
print (str(round(pfolio_vol, 5) * 100) + ' %')

25.453 %