## Diversifiable and Non-Diversifiable Risk of a Portfolio

Import the same dataset we used in the previous lecture – Microsoft and Apple stock, downloaded from Yahoo Finance. Timeframe – 1st of January 2007 until today. <br />
*Hint: To save time, we have written the code you need!*

In [1]:
import numpy as np
import pandas as pd
from pandas_datareader import data as wb
import matplotlib.pyplot as plt
import yfinance as yf

tickers = ['MSFT', 'AAPL']
sec_data = pd.DataFrame()
for t in tickers:
    sec_data[t] = yf.download(t, start='2007-1-1')['Close']
    
sec_data

C:\Users\Admin\AppData\Local\Temp\ipykernel_30132\1838745058.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  sec_data[t] = yf.download(t, start='2007-1-1')['Close']
[*********************100%***********************]  1 of 1 completed
C:\Users\Admin\AppData\Local\Temp\ipykernel_30132\1838745058.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  sec_data[t] = yf.download(t, start='2007-1-1')['Close']
[*********************100%***********************]  1 of 1 completed

                  MSFT        AAPL
Date
2007-01-03   21.161610    2.515686
2007-01-04   21.126171    2.571524
2007-01-05   21.005684    2.553211
2007-01-08   21.211206    2.565819
2007-01-09   21.232470    2.778961
...                ...         ...
2025-10-23  520.559998  259.579987
2025-10-24  523.609985  262.820007
2025-10-27  531.520020  268.809998
2025-10-28  542.070007  269.000000
2025-10-29  541.549988  269.700012

[4737 rows x 2 columns]

In [2]:
sec_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4737 entries, 2007-01-03 to 2025-10-29
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   MSFT    4737 non-null   float64
 1   AAPL    4737 non-null   float64
dtypes: float64(2)
memory usage: 111.0 KB

Then, calculate the diversifiable and the non-diversifiable risk of a portfolio, composed of these two stocks:

a) with weights 0.5 and 0.5;

In [3]:
sec_returns = np.log(sec_data / sec_data.shift(1))
sec_returns

                MSFT      AAPL
Date
2007-01-03       NaN       NaN
2007-01-04 -0.001676  0.021953
2007-01-05 -0.005720 -0.007147
2007-01-08  0.009737  0.004926
2007-01-09  0.001002  0.079799
...              ...       ...
2025-10-23  0.000038  0.004363
2025-10-24  0.005842  0.012405
2025-10-27  0.014994  0.022535
2025-10-28  0.019654  0.000707
2025-10-29 -0.000960  0.002599

[4737 rows x 2 columns]

### Calculating Portfolio Variance

Equal weightings scheme:

In [4]:
weights = np.array([0.5, 0.5])

Portfolio Variance:

In [5]:
pfolio_var = np.dot(weights.T, np.dot(sec_returns.cov() * 250, weights))
pfolio_var

np.float64(0.06842263393921277)

### Calculating Diversifiable and Non-Diversifiable Risk of a Portfolio

Diversifiable Risk:

In [6]:
MSFT_var_a = sec_returns[['MSFT']].var() * 250
MSFT_var_a

MSFT    0.076642
dtype: float64

In [7]:
AAPL_var_a = sec_returns[['AAPL']].var() * 250
AAPL_var_a

AAPL    0.098672
dtype: float64

Or:

In [8]:
MSFT_var_a = sec_returns['MSFT'].var() * 250
MSFT_var_a

np.float64(0.07664173491322152)

In [9]:
AAPL_var_a = sec_returns['AAPL'].var() * 250
AAPL_var_a

np.float64(0.09867203297137454)

Calculating Diversifiable Risk:

In [10]:
dr = pfolio_var - (weights[0] ** 2 * MSFT_var_a) - (weights[1] ** 2 * AAPL_var_a)
dr

np.float64(0.02459419196806376)

In [11]:
print (str(round(dr*100, 3)) + ' %')

2.459 %

Calculating Non-Diversifiable Risk:

In [12]:
n_dr_1 = pfolio_var - dr
n_dr_1

np.float64(0.04382844197114902)

In [13]:
n_dr_2 = (weights[0] ** 2 * MSFT_var_a) + (weights[1] ** 2 * AAPL_var_a)
n_dr_2

np.float64(0.04382844197114902)

*****

b)	With weights 0.2 for Microsoft and 0.8 for Apple.

### Calculating Portfolio Variance

In [14]:
weights_2 = np.array([0.2, 0.8])

Portfolio Variance:

In [15]:
pfolio_var_2 = np.dot(weights_2.T, np.dot(sec_returns.cov() * 250, weights_2))
pfolio_var_2

np.float64(0.0819560533577692)

### Calculating Diversifiable and Non-Diversifiable Risk of a Portfolio

Calculating Diversifiable Risk:

In [16]:
dr_2 = pfolio_var_2 - (weights_2[0] ** 2 * MSFT_var_a) - (weights_2[1] ** 2 * AAPL_var_a)
dr_2

np.float64(0.015740282859560625)

In [17]:
print (str(round(dr*100, 3)) + ' %')

2.459 %

Calculating Non-Diversifiable Risk:

In [18]:
n_dr_2 = pfolio_var_2 - dr_2
n_dr_2

np.float64(0.06621577049820858)

In [19]:
n_dr_2 = (weights_2[0] ** 2 * MSFT_var_a) + (weights_2[1] ** 2 * AAPL_var_a)
n_dr_2

np.float64(0.06621577049820858)