## Calculating Covariance and Correlation

Consider a portfolio composed of *Walmart* and *Facebook*. Do you expect the returns of these companies to show high or low covariance? Or, could you guess what the correlation would be? Will it be closer to 0 or closer to 1?

Begin by extracting data for Walmart and Facebook from the 1st of January 2015 until today.

In [1]:
import numpy as np
import pandas as pd
from pandas_datareader import data as wb
import yfinance as yf

In [2]:
tickers = ['WMT', 'FB']
sec_data = pd.DataFrame()
for t in tickers:
    sec_data[t] = yf.download(t, start='2015-1-1')['Close']

C:\Users\Admin\AppData\Local\Temp\ipykernel_23892\3634216276.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  sec_data[t] = yf.download(t, start='2015-1-1')['Close']
[*********************100%***********************]  1 of 1 completed
C:\Users\Admin\AppData\Local\Temp\ipykernel_23892\3634216276.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  sec_data[t] = yf.download(t, start='2015-1-1')['Close']
[*********************100%***********************]  1 of 1 completed

In [3]:
sec_data.head()

                  WMT  FB
Date
2015-01-02  23.266565 NaN
2015-01-05  23.198854 NaN
2015-01-06  23.377615 NaN
2015-01-07  23.997881 NaN
2015-01-08  24.504379 NaN

In [4]:
returns = np.log(sec_data / sec_data.shift(1))
returns

                 WMT        FB
Date
2015-01-02       NaN       NaN
2015-01-05 -0.002914       NaN
2015-01-06  0.007676       NaN
2015-01-07  0.026187       NaN
2015-01-08  0.020886       NaN
...              ...       ...
2025-10-23 -0.002617  0.002844
2025-10-24 -0.006478  0.003292
2025-10-27 -0.016142  0.004762
2025-10-28 -0.012522  0.002122
2025-10-29 -0.006906 -0.000381

[2723 rows x 2 columns]

Repeat the process we went through in the lecture for these two stocks. How would you explain the difference between their means and their standard deviations?

In [5]:
returns[['WMT', 'FB']].mean() * 250

WMT    0.136155
FB     0.154142
dtype: float64

In [6]:
returns[['WMT', 'FB']].std() * 250 ** 0.5

WMT    0.213872
FB     0.053595
dtype: float64

***

## Covariance and Correlation


\begin{eqnarray*}
Covariance Matrix: \  \   
\Sigma = \begin{bmatrix}
        \sigma_{1}^2 \ \sigma_{12} \ \dots \ \sigma_{1I} \\
        \sigma_{21} \ \sigma_{2}^2 \ \dots \ \sigma_{2I} \\
        \vdots \ \vdots \ \ddots \ \vdots \\
        \sigma_{I1} \ \sigma_{I2} \ \dots \ \sigma_{I}^2
    \end{bmatrix}
\end{eqnarray*}

Covariance matrix:

In [7]:
cov_matrix = returns.cov()
cov_matrix

          WMT        FB
WMT  0.000183  0.000005
FB   0.000005  0.000011

Correlation matrix:

In [8]:
cov_matrix_a = returns.cov() * 250
cov_matrix_a

          WMT        FB
WMT  0.045741  0.001291
FB   0.001291  0.002872

In [9]:
corr_matrix = returns.corr()
corr_matrix

          WMT        FB
WMT  1.000000  0.121337
FB   0.121337  1.000000

Would you consider investing in such a portfolio?