## Calculating Covariance and Correlation

Consider a portfolio composed of *Walmart* and *Facebook*. Do you expect the returns of these companies to show high or low covariance? Or, could you guess what the correlation would be? Will it be closer to 0 or closer to 1?

Begin by extracting data for Walmart and Facebook from the 1st of January 2014 until today.

In [1]:
import numpy as np
import pandas as pd
from pandas_datareader import data as wb

In [2]:
sec_data = pd.read_csv(r'C:\Users\Admin\OneDrive\Documents\bt ptdl\bt_tuan_ptdl\DA07 - Phan tich du lieu tai chinh\02_risks\02_risks\02_Calculating Covariance and Correlation\02_Calculating Covariance and Correlation\csv\Walmart_FB_2014_2017.csv', index_col='Date')

In [3]:
sec_data.head()

                  WMT         FB
Date
2013-12-31  71.126411  54.650002
2014-01-02  71.325287  54.709999
2014-01-03  71.090279  54.560001
2014-01-06  70.692558  57.200001
2014-01-07  70.909485  57.919998

In [4]:
returns = np.log(sec_data / sec_data.shift(1))
returns

                 WMT        FB
Date
2013-12-31       NaN       NaN
2014-01-02  0.002792  0.001097
2014-01-03 -0.003300 -0.002745
2014-01-06 -0.005610  0.047253
2014-01-07  0.003064  0.012509
...              ...       ...
2017-04-03 -0.003474  0.001618
2017-04-04  0.002503 -0.003873
2017-04-05 -0.005012  0.000846
2017-04-06 -0.003075 -0.004805
2017-04-07  0.020371 -0.002766

[824 rows x 2 columns]

Repeat the process we went through in the lecture for these two stocks. How would you explain the difference between their means and their standard deviations?

In [5]:
returns[['WMT', 'FB']].mean() * 250

WMT    0.003551
FB     0.287439
dtype: float64

In [6]:
returns[['WMT', 'FB']].std() * 250 ** 0.5

WMT    0.177607
FB     0.287726
dtype: float64

***

## Covariance and Correlation


\begin{eqnarray*}
Covariance Matrix: \  \   
\Sigma = \begin{bmatrix}
        \sigma_{1}^2 \ \sigma_{12} \ \dots \ \sigma_{1I} \\
        \sigma_{21} \ \sigma_{2}^2 \ \dots \ \sigma_{2I} \\
        \vdots \ \vdots \ \ddots \ \vdots \\
        \sigma_{I1} \ \sigma_{I2} \ \dots \ \sigma_{I}^2
    \end{bmatrix}
\end{eqnarray*}

Covariance matrix:

In [7]:
cov_matrix = returns.cov()
cov_matrix

          WMT        FB
WMT  0.000126  0.000035
FB   0.000035  0.000331

Correlation matrix:

In [8]:
cov_matrix_a = returns.cov() * 250
cov_matrix_a

          WMT        FB
WMT  0.031544  0.008777
FB   0.008777  0.082786

In [9]:
corr_matrix = returns.corr()
corr_matrix

          WMT        FB
WMT  1.000000  0.171746
FB   0.171746  1.000000

Would you consider investing in such a portfolio?