## Calculating Portfolio Risk

Calculate the risk of an equally weighted portfolio composed of Microsoft and Apple. The data can be obtained from *MSFT_AAPL_2000_2017.csv*.

*Hint: The code we went through in the lecture is what you need here. You will need to import the data first. The previous lessons could be a good reference point for that! :) *

In [1]:
import numpy as np
import pandas as pd
from pandas_datareader import data as wb
import matplotlib.pyplot as plt

In [2]:
sec_data = pd.read_csv(r'C:\Users\Admin\OneDrive\Documents\bt ptdl\bt_tuan_ptdl\DA07 - Phan tich du lieu tai chinh\02_risks\02_risks\03_Calculating Portfolio Risk\03_Calculating Portfolio Risk\csv\MSFT_AAPL_2000_2017.csv', index_col='Date')

In [3]:
sec_data.tail()

                 MSFT        AAPL
Date
2017-03-17  64.158463  138.869217
2017-03-20  64.217804  140.327454
2017-03-21  63.505699  138.720413
2017-03-22  64.316704  140.287766
2017-03-23  64.158463  139.791763

In [4]:
sec_returns = np.log(sec_data / sec_data.shift(1))

In [5]:
sec_returns

                MSFT      AAPL
Date
1999-12-31       NaN       NaN
2000-01-03 -0.001607  0.085034
2000-01-04 -0.034364 -0.088078
2000-01-05  0.010489  0.014528
2000-01-06 -0.034072 -0.090514
...              ...       ...
2017-03-17  0.003552 -0.004988
2017-03-20  0.000924  0.010446
2017-03-21 -0.011151 -0.011518
2017-03-22  0.012690  0.011235
2017-03-23 -0.002463 -0.003542

[4334 rows x 2 columns]

## MSFT

In [6]:
sec_returns['MSFT'].mean()

np.float64(0.00011508712580239269)

In [7]:
sec_returns['MSFT'].mean() * 250

np.float64(0.028771781450598173)

In [8]:
sec_returns['MSFT'].std()

np.float64(0.01965694884940363)

## Apple

In [9]:
sec_returns['AAPL'].mean()

np.float64(0.0008643420491903574)

In [10]:
sec_returns['AAPL'].mean() * 250

np.float64(0.21608551229758935)

In [11]:
sec_returns['AAPL'].std()

np.float64(0.027761934312069407)

In [12]:
sec_returns['AAPL'].std() * 250 ** 0.5

np.float64(0.43895472339059544)

In [13]:
sec_returns[['MSFT', 'AAPL']].mean() * 250

MSFT    0.028772
AAPL    0.216086
dtype: float64

In [14]:
sec_returns[['MSFT', 'AAPL']].std() * 250 ** 0.5

MSFT    0.310804
AAPL    0.438955
dtype: float64

***

## Covariance and Correlation


\begin{eqnarray*}
Covariance Matrix: \  \   
\Sigma = \begin{bmatrix}
        \sigma_{1}^2 \ \sigma_{12} \ \dots \ \sigma_{1I} \\
        \sigma_{21} \ \sigma_{2}^2 \ \dots \ \sigma_{2I} \\
        \vdots \ \vdots \ \ddots \ \vdots \\
        \sigma_{I1} \ \sigma_{I2} \ \dots \ \sigma_{I}^2
    \end{bmatrix}
\end{eqnarray*}

*****

Covariance matrix:

In [15]:
cov_matrix = sec_returns.cov()
cov_matrix

          MSFT      AAPL
MSFT  0.000386  0.000218
AAPL  0.000218  0.000771

In [16]:
cov_matrix_a = sec_returns.cov() * 250
cov_matrix_a

          MSFT      AAPL
MSFT  0.096599  0.054592
AAPL  0.054592  0.192681

***

Correlation matrix:

In [17]:
corr_matrix = sec_returns.corr()
corr_matrix

          MSFT      AAPL
MSFT  1.000000  0.400153
AAPL  0.400153  1.000000

## Calculating Portfolio Risk

Equal weigthing scheme:

In [18]:
weights = np.array([0.5, 0.5])

Portfolio Variance:

In [19]:
pfolio_var = np.dot(weights.T, np.dot(sec_returns.cov() * 250, weights))
pfolio_var

np.float64(0.09961622870546066)

Portfolio Volatility:

In [20]:
pfolio_vol = (np.dot(weights.T, np.dot(sec_returns.cov() * 250, weights))) ** 0.5
pfolio_vol

np.float64(0.31562038702444534)

In [21]:
print (str(round(pfolio_vol, 5) * 100) + ' %')

31.562 %